"""Database schema update.

Revision ID: 6866e0b9e8f1
Revises: c3b3b466c40c
Create Date: 2025-07-17 15:19:21.415112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6866e0b9e8f1'
down_revision = 'c3b3b466c40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
